version: "3.9"

services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001      

  script:
    build:
      context: ./app
      dockerfile: ./script/Dockerfile
    network_mode: "service:app"
